spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: Merei99Merei99
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  port: 8087

